name: Emerald
version: ${project.version}
main: io.github.zowpy.emerald.EmeraldPlugin
authors: [ Zowpy ]
commands:
  serverinfo:
    aliases:
      - servers
      - si
      - serveri
      - sinfo
  servers: